Information = {
    "Acacia": "Acacia has various medicinal benefits including its use in treating respiratory issues, wound healing, and as a digestive aid.",
    "Ajwain": "Ajwain, also known as carom seeds, is used in traditional medicine for its digestive properties and to relieve stomach ailments.",
    "AloeVera": "Aloe vera is well-known for its medicinal properties, including its use in skincare, wound healing, and as a digestive aid.",
    "Amaltas": "Amaltas, also known as Indian laburnum, is used in traditional medicine for its laxative and purgative properties.",
    "Amla": "Amla, or Indian gooseberry, is rich in vitamin C and is used in Ayurvedic medicine for its antioxidant properties and to boost immunity.",
    "Anantamul": "Anantamul is a traditional herb used in Ayurvedic medicine for its anti-inflammatory and detoxifying properties.",
    "Ankur": "Ankur, or sprouted grains, are rich in nutrients and enzymes and are considered beneficial for overall health and digestion.",
    "Aquatic-Ginger": "Aquatic ginger, or Shati, is used in Ayurvedic medicine for its anti-inflammatory and digestive properties.",
    "Ashoka": "Ashoka tree bark is used in traditional medicine for its uterine tonic and anti-inflammatory properties, and to treat menstrual disorders.",
    "Ashwagandha": "Ashwagandha is an adaptogenic herb used in Ayurvedic medicine to reduce stress, improve cognitive function, and boost immunity.",
    "Bael": "Bael fruit is used in traditional medicine for its digestive and anti-inflammatory properties, and to treat diarrhea and dysentery.",
    "Belladonna": "Belladonna, also known as deadly nightshade, has medicinal uses in treating various conditions like muscle spasms, motion sickness, and Parkinson's disease.",
    "Belpatra": "Belpatra, or leaves of the bael tree, are used in Ayurvedic medicine for their anti-inflammatory, antimicrobial, and digestive properties.",
    "Cardamom": "Cardamom is used in traditional medicine for its digestive, carminative, and antimicrobial properties.",
    "Castor Oil Plant": "Castor oil is derived from the seeds of the castor oil plant and is used in traditional medicine as a laxative and for skin conditions.",
    "Celosia-Argentea": "Celosia argentea, also known as cockscomb, has medicinal properties and is used in traditional medicine for treating various ailments including digestive issues and skin conditions.",
    "Champa": "Champa, or Plumeria, has medicinal uses in traditional medicine for its anti-inflammatory, analgesic, and antimicrobial properties.",
    "Chinese-Ixora": "Chinese ixora is used in traditional medicine for its anti-inflammatory and analgesic properties, and to treat various conditions like arthritis and diarrhea.",
    "Chirata": "Chirata is a bitter herb used in traditional medicine for its digestive and liver-protective properties, and to treat fever and infections.",
    "Cinnamon": "Cinnamon has medicinal properties and is used in traditional medicine for its anti-inflammatory, antioxidant, and antimicrobial effects.",
    "Coleus": "Coleus, or Coleus forskohlii, is used in traditional medicine for its anti-inflammatory, antimicrobial, and weight loss properties.",
    "Common Ivy": "Common ivy, or Hedera helix, has medicinal uses in traditional medicine for its anti-inflammatory, expectorant, and analgesic properties.",
    "CopperLeaf": "Copperleaf, or Acalypha indica, is used in traditional medicine for its anti-inflammatory, antimicrobial, and wound-healing properties.",
    "Coptis": "Coptis, or goldthread, has medicinal uses in traditional Chinese medicine for its antimicrobial, anti-inflammatory, and digestive properties.",
    "Cyprus": "Cyprus, or cypress, has medicinal properties and is used in traditional medicine for its astringent, antimicrobial, and antispasmodic effects.",
    "Datura": "Datura has medicinal uses in traditional medicine for its analgesic, antispasmodic, and sedative properties, but can be toxic if ingested improperly.",
    "Dill": "Dill is used in traditional medicine for its digestive, antimicrobial, and anti-inflammatory properties.",
    "Fenugreek": "Fenugreek is used in traditional medicine for its digestive, anti-inflammatory, and lactation-promoting properties.",
    "Gokharu": "Gokharu, or Tribulus terrestris, is used in traditional medicine for its diuretic, aphrodisiac, and anti-inflammatory properties.",
    "Gugal": "Gugal, or guggul, is used in Ayurvedic medicine for its anti-inflammatory, lipid-lowering, and antioxidant properties.",
    "Guggul": "Guggul, or Indian bdellium, is used in Ayurvedic medicine for its anti-inflammatory, lipid-lowering, and antioxidant properties.",
    "Henbane": "Henbane has medicinal uses in traditional medicine for its analgesic, sedative, and antispasmodic properties, but can be toxic if ingested improperly.",
    "Henna": "Henna is used in traditional medicine for its cooling, astringent, and antimicrobial properties, and is also used for hair dyeing and conditioning.",
    "Horse Nettle Berries": "Horse nettle berries have medicinal uses in traditional medicine for treating skin conditions, rheumatism, and as a diuretic.",
    "Houseleek": "Houseleek, or Sempervivum tectorum, has medicinal properties and is used in traditional medicine for treating burns, wounds, and skin conditions.",
    "Indian Birthwort": "Indian birthwort, or Aristolochia indica, has medicinal uses in traditional medicine for treating respiratory issues, fever, and gastrointestinal disorders.",
    "Indian Pulai": "Indian pulai, or Alstonia scholaris, has medicinal properties and is used in traditional medicine for treating fever, diarrhea, and skin conditions.",
    "Indrajav Seeda": "Indrajav seed, or Holarrhena antidysenterica, has medicinal uses in traditional medicine for treating dysentery, diarrhea, and digestive disorders.",
    "Ipecac": "Ipecac, or ipecacuanha, has medicinal uses in traditional medicine for inducing vomiting and treating poisoning.",
    "Isabghul": "Isabghul, or psyllium husk, is used in traditional medicine for its laxative and cholesterol-lowering properties.",
    "Ivy Leaved Violet": "Ivy-leaved violet, or Viola hederacea, has medicinal properties and is used in traditional medicine for treating cough, sore throat, and respiratory issues.",
    "Jamun": "Jamun, or Syzygium cumini, has medicinal uses in traditional medicine for treating diabetes, digestive issues, and skin conditions.",
    "Jasmine": "Jasmine has medicinal properties and is used in traditional medicine for its sedative, antidepressant, and antispasmodic effects.",
    "Jatamansi": "Jatamansi, or Nardostachys jatamansi, is used in traditional medicine for its calming, sedative, and neuroprotective properties.",
    "Kali Musli": "Kali musli, or Curculigo orchioides, is used in traditional medicine as an aphrodisiac, adaptogen, and anti-inflammatory agent.",
    "Kandankathiri": "Kandankathiri, or Solanum nigrum, has medicinal properties and is used in traditional medicine for treating fever, cough, and respiratory issues.",
    "Kateri": "Kateri, or Cucumis aculeatus, has medicinal uses in traditional medicine for treating skin conditions, fever, and urinary disorders.",
    "Kirmala": "Kirmala, or Strychnos nux-vomica, has medicinal properties and is used in traditional medicine for treating digestive issues, nervous disorders, and as a tonic.",
    "Kokilaksha": "Kokilaksha, or Asteracantha longifolia, has medicinal uses in traditional medicine for treating urinary disorders, impotence, and as an aphrodisiac.",
    "Kutaja": "Kutaja, or Holarrhena antidysenterica, has medicinal properties and is used in traditional medicine for treating diarrhea, dysentery, and digestive issues.",
    "Kutki": "Kutki, or Picrorhiza kurroa, has medicinal uses in traditional medicine for treating liver disorders, fever, and respiratory issues.",
    "Lavender": "Lavender has medicinal properties and is used in traditional medicine for its calming, analgesic, and antimicrobial effects.",
    "Licquorice": "Licorice, or Glycyrrhiza glabra, has medicinal uses in traditional medicine for treating respiratory issues, digestive disorders, and as an anti-inflammatory agent.",
    "Lipstick-Plant": "Lipstick plant, or Aeschynanthus radicans, has medicinal properties and is used in traditional medicine for treating skin conditions, fever, and infections.",
    "Madhuca Indica": "Madhuca indica, or mahua, has medicinal uses in traditional medicine for its anti-inflammatory, analgesic, and aphrodisiac properties.",
    "Mahua": "Mahua, or Madhuca longifolia, has medicinal properties and is used in traditional medicine for treating respiratory issues, fever, and skin conditions.",
    "Malabar Nut": "Malabar nut, or Justicia adhatoda, has medicinal uses in traditional medicine for treating respiratory issues, asthma, and bronchitis.",
    "Medicinal-Arive Dantu": "Arive dantu, or Solanum trilobatum, has medicinal properties and is used in traditional medicine for treating respiratory issues, fever, and digestive disorders.",
    "Medicinal-Basale": "Basale, or Basella alba, has medicinal uses in traditional medicine for treating digestive issues, skin conditions, and as a tonic.",
    "Medicinal-Neem": "Neem, or Azadirachta indica, has medicinal properties and is used in traditional medicine for its antimicrobial, anti-inflammatory, and antipyretic effects.",
    "Medicinal-Rose Apple": "Rose apple, or Syzygium jambos, has medicinal uses in traditional medicine for treating digestive issues, fever, and skin conditions.",
    "Medicinal-Sandalwood": "Sandalwood has medicinal properties and is used in traditional medicine for its cooling, anti-inflammatory, and antimicrobial effects.",
    "Meetha": "Meetha, or honey, has medicinal uses in traditional medicine for treating cough, sore throat, and wound healing.",
    "Morning Glory": "Morning glory, or Ipomoea, has medicinal properties and is used in traditional medicine for treating insomnia, anxiety, and as a laxative.",
    "Mountain Peanut": "Mountain peanut, or Stylosanthes fruticosa, has medicinal uses in traditional medicine for treating fever, cough, and digestive disorders.",
    "Mulethi": "Mulethi, or licorice root, has medicinal properties and is used in traditional medicine for treating respiratory issues, digestive disorders, and as an anti-inflammatory agent.",
    "Nardostachys jatamans": "Nardostachys jatamansi, or spikenard, has medicinal uses in traditional medicine for its calming, sedative, and neuroprotective properties.",
    "Nepal Yam": "Nepal yam, or Dioscorea deltoidea, has medicinal properties and is used in traditional medicine for treating digestive issues, fever, and as a tonic.",
    "Nettle": "Nettle has medicinal properties and is used in traditional medicine for treating allergies, arthritis, and as a diuretic.",
    "OLEANDER": "Oleander has medicinal uses in traditional medicine for treating heart conditions, asthma, and as a laxative, but can be toxic if ingested improperly.",
    "Oleander": "Oleander has medicinal uses in traditional medicine for treating heart conditions, asthma, and as a laxative, but can be toxic if ingested improperly.",
    "Olive": "Olive has medicinal properties and is used in traditional medicine for its cardiovascular benefits, antioxidant effects, and as an anti-inflammatory agent.",
    "Palash": "Palash, or Butea monosperma, has medicinal uses in traditional medicine for treating skin conditions, fever, and digestive disorders.",
    "Picrorhiza kurroa": "Picrorhiza kurroa, or kutki, has medicinal properties and is used in traditional medicine for treating liver disorders, fever, and respiratory issues.",
    "Pine": "Pine has medicinal properties and is used in traditional medicine for its anti-inflammatory, antimicrobial, and expectorant effects.",
    "Plantago Ovata": "Plantago ovata, or psyllium, has medicinal uses in traditional medicine for its laxative and cholesterol-lowering properties.",
    "Puncture Vine": "Puncture vine, or Tribulus terrestris, has medicinal properties and is used in traditional medicine for treating urinary disorders, impotence, and as an aphrodisiac.",
    "Ricinus": "Ricinus, or castor oil plant, has medicinal uses in traditional medicine for its laxative properties and as a remedy for skin conditions.",
    "Rosary Pea": "Rosary pea, or Abrus precatorius, has medicinal properties and is used in traditional medicine for treating respiratory issues, fever, and as an analgesic.",
    "Sadabahar": "Sadabahar, or periwinkle, has medicinal uses in traditional medicine for treating diabetes, cancer, and as an antipyretic.",
    "Sadaphuli": "Sadaphuli, or Vinca rosea, has medicinal properties and is used in traditional medicine for treating diabetes, cancer, and as an antipyretic.",
    "Sandalwood": "Sandalwood has medicinal properties and is used in traditional medicine for its cooling, anti-inflammatory, and antimicrobial effects.",
    "Saussurea Costus": "Saussurea costus, or costus, has medicinal uses in traditional medicine for its anti-inflammatory, digestive, and antimicrobial properties.",
    "Serpentine Root": "Serpentine root, or Rauwolfia serpentina, has medicinal properties and is used in traditional medicine for treating hypertension, insomnia, and anxiety.",
    "Silverleaf Nightshade": "Silverleaf nightshade, or Solanum elaeagnifolium, has medicinal uses in traditional medicine for treating respiratory issues, fever, and digestive disorders.",
    "Simpoh-Lak": "Simpoh lak, or Dillenia suffruticosa, has medicinal properties and is used in traditional medicine for treating skin conditions, fever, and as an analgesic.",
    "Solanum Incanum": "Solanum incanum, or thorny nightshade, has medicinal uses in traditional medicine for treating respiratory issues, fever, and digestive disorders.",
    "Solanum Xanthocarpum": "Solanum xanthocarpum, or yellow berried nightshade, has medicinal properties and is used in traditional medicine for treating respiratory issues, fever, and digestive disorders.",
    "Somavalli": "Somavalli, or Sida cordifolia, has medicinal uses in traditional medicine for treating respiratory issues, fever, and as a tonic.",
    "Sweet Basil": "Sweet basil, or Ocimum basilicum, has medicinal properties and is used in traditional medicine for treating digestive issues, respiratory conditions, and as an anti-inflammatory agent.",
    "Syzygium cumini (L": "Syzygium cumini, or jamun, has medicinal uses in traditional medicine for treating diabetes, digestive issues, and skin conditions.",
    "Tamarind": "Tamarind has medicinal properties and is used in traditional medicine for its laxative, digestive, and anti-inflammatory effects.",
    "Thai Eggplant": "Thai eggplant, or Solanum melongena, has medicinal uses in traditional medicine for treating digestive issues, fever, and as a diuretic.",
    "Thyme": "Thyme has medicinal properties and is used in traditional medicine for treating respiratory issues, digestive disorders, and as an antimicrobial agent.",
    "Ti": "Ti, or Cordyline fruticosa, has medicinal uses in traditional medicine for treating skin conditions, fever, and as an analgesic.",
    "Triphala": "Triphala is an Ayurvedic herbal remedy consisting of three fruits - Amalaki, Bibhitaki, and Haritaki. It is used for digestive health, detoxification, and as a general tonic.",
    "Turmeric": "Turmeric has medicinal properties and is used in traditional medicine for its anti-inflammatory, antioxidant, and digestive benefits.",
    "Turpeth": "Turpeth, or Operculina turpethum, has medicinal uses in traditional medicine for treating digestive issues, liver disorders, and as a laxative.",
    "Utranajutuka": "Utranajutuka, or Physalis angulata, has medicinal properties and is used in traditional medicine for treating skin conditions, fever, and as an analgesic.",
    "Vilvam Tree": "Vilvam tree, or Aegle marmelos, has medicinal uses in traditional medicine for treating digestive issues, fever, and as a tonic.",
    "Visadodi": "Visadodi, or Aconitum ferox, has medicinal properties and is used in traditional medicine for treating fever, pain, and as an anti-inflammatory agent.",
    "Wood Rose": "Wood rose, or Merremia umbellata, has medicinal uses in traditional medicine for treating respiratory issues, fever, and digestive disorders.",
    "Wormwood": "Wormwood, or Artemisia absinthium, has medicinal properties and is used in traditional medicine for treating digestive issues, fever, and as an antimicrobial agent.",
    "Yam": "Yam has medicinal uses in traditional medicine for treating digestive issues, fever, and as a tonic.",
    "ambrosia": "Ambrosia has medicinal properties and is used in traditional medicine for treating allergies, respiratory issues, and as an anti-inflammatory agent.",
    "coscinium fenestratum": "Coscinium fenestratum, or tree turmeric, has medicinal uses in traditional medicine for treating digestive issues, fever, and as an antimicrobial agent.",
    "curcuma longa": "Curcuma longa, or turmeric, has medicinal properties and is used in traditional medicine for its anti-inflammatory, antioxidant, and digestive benefits.",
    "hygrophila auriculata": "Hygrophila auriculata, or gokshura, has medicinal uses in traditional medicine for treating urinary disorders, kidney stones, and as an aphrodisiac.",
    "indian sarsaparilla": "Indian sarsaparilla, or Hemidesmus indicus, has medicinal properties and is used in traditional medicine for treating skin conditions, fever, and as a tonic.",
    "lemongrass": "Lemongrass has medicinal properties and is used in traditional medicine for its digestive, anti-inflammatory, and antimicrobial effects.",
    "neem": "Neem, or Azadirachta indica, has medicinal properties and is used in traditional medicine for its antimicrobial, anti-inflammatory, and antipyretic effects.",
    "syzygium cumin (L.) Skeel": "Syzygium cumin (L.) Skeel, or jamun, has medicinal uses in traditional medicine for treating diabetes, digestive issues, and skin conditions.",
        "Alpinia Galanga (Rasna)": "Alpinia Galanga, commonly known as Rasna, is a medicinal herb native to Southeast Asia, prized for its culinary and therapeutic properties. It is often used in traditional medicine for its anti-inflammatory and digestive benefits.",
    "Amaranthus Viridis (Arive-Dantu)": "Amaranthus Viridis, commonly known as Arive-Dantu, is a nutritious leafy green vegetable rich in vitamins and minerals. It is widely cultivated in various regions for its edible leaves and seeds.",
    "Artocarpus Heterophyllus (Jackfruit)": "Artocarpus heterophyllus, commonly known as jackfruit, is a tropical tree native to southwest India. Its large, spiky fruits are renowned for their sweet flavor and versatility in culinary applications.",
    "Azadirachta Indica (Neem)": "Azadirachta Indica, commonly known as Neem, is a versatile tree native to the Indian subcontinent, prized for its medicinal properties and its use in various industries such as agriculture, cosmetics, and pharmaceuticals.",
    "Basella Alba (Basale)": "Basella Alba, commonly known as Basale, is a nutritious leafy vegetable rich in vitamins and minerals, popular in Asian and African cuisines for its tender leaves and mild flavor. It is often used in salads, soups, and stir-fries.",
    "Brassica Juncea (Indian Mustard)": "Brassica Juncea, commonly known as Indian Mustard, is a versatile plant cultivated for its seeds and leaves, widely used in Indian cuisine. It is prized for its pungent flavor and is a rich source of nutrients like vitamins and minerals.",
    "Carissa Carandas (Karanda)": "Carissa Carandas, commonly known as Karanda, is a tropical fruit-bearing shrub native to the Indian subcontinent, prized for its tart, cranberry-like flavor. Its small, berry-like fruits are rich in vitamin C and used in culinary and medicinal applications.",
    "Citrus Limon (Lemon)": "Citrus limon, commonly known as lemon, is a species of evergreen tree native to Asia. Its tart yellow fruit is widely used in culinary, medicinal, and cosmetic applications worldwide.",
    "Ficus Auriculata (Roxburgh fig)": "Ficus Auriculata, commonly known as Roxburgh fig, is a species of fig tree native to Southeast Asia. It is distinguished by its large, ear-shaped leaves and small, edible figs.",
    "Ficus Religiosa (Peepal Tree)": "Ficus Religiosa, commonly known as the Peepal Tree, holds significant cultural and religious importance in many traditions, revered for its spiritual symbolism and medicinal properties. It is considered sacred in Hinduism, Buddhism, and Jainism.",
    "Hibiscus Rosa-sinensis": "Hibiscus Rosa-sinensis, commonly known as Chinese hibiscus or shoe flower, is a tropical plant prized for its vibrant flowers, which come in various colors and are often used ornamentally or in herbal remedies.",
    "Jasminum (Jasmine)": "Jasminum, commonly known as Jasmine, is a genus of shrubs and vines in the olive family, prized for its fragrant white or yellow flowers. Widely cultivated for ornamental and ceremonial purposes, Jasmine is also utilized in perfumery and traditional medicine.",
    "Mangifera Indica (Mango)": '"Mangifera Indica, commonly known as mango, is a tropical fruit tree native to South Asia, prized for its sweet and juicy fruits."',
    "Mentha (Mint)": "Mentha, commonly known as mint, is a perennial herb known for its refreshing aroma and culinary uses. It is widely cultivated for its menthol-rich leaves, which are utilized in teas, beverages, and various culinary dishes.",
    "Moringa Oleifera (Drumstick)": "Moringa Oleifera, commonly known as Drumstick, is a nutritious plant prized for its edible pods and leaves, packed with vitamins, minerals, and antioxidants. It is revered for its potential health benefits and is used in various culinary and medicinal applications worldwide.",
    "Muntingia Calabura (Jamaica Cherry-Gasagase)": "Muntingia calabura, commonly known as Jamaica Cherry or Gasagase, is a fast-growing evergreen tree producing small, sweet-tasting red berries. Native to tropical regions, it is valued for its ornamental beauty and edible fruit.",
    "Murraya Koenigii (Curry)": "Murraya Koenigii, commonly known as curry leaves, is a tropical tree native to India and Sri Lanka, prized for its aromatic leaves used in South Asian cuisine for flavoring curries and other dishes. These leaves are rich in antioxidants and have potential health benefits.",
    "Nerium Oleander (Oleander)": "Nerium Oleander, commonly known as Oleander, is a highly toxic flowering shrub native to the Mediterranean region. Its vibrant flowers come in various colors and it is often used in landscaping despite its poisonous nature.",
    "Nyctanthes Arbor-tristis (Parijata)": "Nyctanthes Arbor-tristis, commonly known as Parijata, is a fragrant flowering plant native to South Asia, revered in Hindu mythology. Its white flowers with orange centers bloom at night, emitting a delightful scent, making it a symbol of beauty and spirituality.",
    "Ocimum Tenuiflorum (Tulsi)": "Ocimum tenuiflorum, commonly known as Tulsi or Holy Basil, is a revered herb in Hindu culture for its medicinal properties and spiritual significance. It is used in traditional medicine for its anti-inflammatory, antioxidant, and adaptogenic effects.",
    "Piper Betle (Betel)": "Piper Betle, commonly known as betel leaf, is a tropical evergreen vine famous for its cultural and medicinal significance in South and Southeast Asia. It is traditionally chewed with areca nut and lime as a stimulant and in religious ceremonies.",
    "Plectranthus Amboinicus (Mexican Mint)": "Plectranthus Amboinicus, also known as Mexican Mint or Cuban Oregano, is a perennial herb native to Southern and Eastern Africa. It is prized for its aromatic leaves used in culinary dishes and traditional medicine for its purported health benefits.",
    "Pongamia Pinnata (Indian Beech)": "Pongamia pinnata, commonly known as Indian Beech, is a tropical tree native to South Asia. It is valued for its oil-rich seeds used in biodiesel production and its potential in reforestation and soil improvement.",
    "Psidium Guajava (Guava)": "Psidium Guajava, commonly known as Guava, is a tropical fruit-bearing tree native to Central America, known for its sweet, aromatic flavor and rich nutritional profile. It is prized for its high vitamin C content and is utilized in various culinary dishes and beverages worldwide.",
    "Punica Granatum (Pomegranate)": "Punica granatum, commonly known as pomegranate, is a fruit-bearing shrub or small tree native to the region of Iran to northern India. It is prized for its juicy arils packed with antioxidants and vitamins, often consumed fresh or used in various culinary and medicinal applications.",
    "Santalum Album (Sandalwood)": "Santalum album, commonly known as sandalwood, is a fragrant tree species prized for its aromatic heartwood, extensively used in perfumery, skincare, and religious rituals. Its oil is renowned for its calming aroma and has been historically valued in various cultural and medicinal practices.",
    "Syzygium Cumini (Jamun)": "Syzygium Cumini, commonly known as Jamun or Indian blackberry, is a tropical tree native to the Indian subcontinent. Its fruit is purplish-black, rich in antioxidants, and is used in traditional medicine and culinary dishes.",
    "Syzygium Jambos (Rose Apple)": "Syzygium Jambos, commonly known as Rose Apple, is a tropical tree native to Southeast Asia, prized for its fragrant, bell-shaped fruits. The fruit has a crisp texture and a mild, slightly floral flavor, making it popular in salads, desserts, and beverages.",
    "Tabernaemontana Divaricata (Crape Jasmine)": "Tabernaemontana divaricata, commonly known as Crape Jasmine, is a tropical evergreen shrub prized for its fragrant white flowers and glossy foliage, often used in traditional medicine and ornamental gardening.",
    "Trigonella Foenum-graecum (Fenugreek)": "Trigonella Foenum-graecum, commonly known as Fenugreek, is an herbaceous plant renowned for its culinary and medicinal uses, prized for its distinctive flavor and potential health benefits, including aiding digestion and controlling blood sugar levels",
    
}


def BotanicalInf(name):
    try:
        return Information[name]
    except KeyError:
        return f"No information available for '{name}'"
